### ISSUE TITLE
Question for the devs

### ISSUE THREAD

**Issue by lulivi** [lulivi/dgp-lib#2]
I have some quick points to change before uploading the library.

- What do you think about changing the `src` directory to `dgp` or whatever name you think fits better there and `deep_g_prop.py` to `__main__.py` as it will be the entry point of the package?
- What do you think about getting rid of `src/hp_optimization/` and `src/mlp_frameworks/` as this repository will contain only the library and some useful scripts (`src/models` doesn't make any sense since the models in it are not used anymore. I will get rid of it with the others)?

cc/ @JJ @mariosky @pacastillo

**Comment by JJ** [comment]
1. Yes.
2. Yes
